version: '2'
services:
  app:
    build: .
    container_name: "twasi-redirector"
    image: debian/latest
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: "twasi-redirector"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles
